name: Deploy Viewer to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'tnits-katalog/src/main/resources/static/viewer.html'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy to gh-pages
        run: |
          # Save the viewer.html content
          cp tnits-katalog/src/main/resources/static/viewer.html /tmp/viewer.html

          # Switch to gh-pages branch
          git checkout gh-pages

          # Copy viewer.html as index.html
          cp /tmp/viewer.html index.html

          # Commit and push if there are changes
          if git diff --quiet index.html; then
            echo "No changes to deploy"
          else
            git add index.html
            git commit -m "Update viewer from main branch"
            git push origin gh-pages
          fi
